### ISSUE TITLE
getNoteContent MemBuffer overrun

### ISSUE THREAD

**Issue by andyb** [evernote/evernote-sdk-js#65]
Hi,

Seeing the following issue when calling getNoteContent()

```
/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/transport/memBuffer.js:29
    if (this.offset + len > this.buffer.length) throw Error('MemBuffer overrun');
                                                ^

Error: MemBuffer overrun
    at Error (native)
    at MemBuffer.read (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/transport/memBuffer.js:29:55)
    at BinaryProtocol.readString (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/protocol/binaryProtocol.j
s:333:29)
    at BinaryProtocol.readType (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/protocol/binaryProtocol.js:
353:25)
    at Object.Thrift.Struct.readFields (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/thrift.js:505:49)
    at Thrift.Struct.read (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/thrift.js:485:19)

    at Thrift.Method.processResponse (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/thrift.js:204:26)
    at null.<anonymous> (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/thrift.js:165:42)
    at wrapTransport (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/protocol/binaryProtocol.js:48:20)
    at IncomingMessage.<anonymous> (/Users/andy.britcliffe/code/action/node_modules/evernote/lib/thrift/transport/binaryHttpTra
nsport.js:77:27)
```

Code is:

```
var noteStore = authClient.getNoteStore();
  var filter = {
    words: searchText,
  };

  noteStore.findNotesMetadata(
      filter,
      0,
      100,
      {
            includeTitle: true,
            includeContentLength: true,
            includeCreated: true,
            includeUpdated: true
        }
  ).then(function(res) {
    for (var i = 0; i < res.notes.length; i++) {
      noteStore.getNoteContent(res.notes[i].guid).then(function(note){
          console.log(note);
      });
    }
  })
```

Using  v6.9.2

Looks like someone has seen something similar here: http://stackoverflow.com/questions/41189736/how-to-avoid-membuffer-overrun-in-node-js-evernote-api-2-0-0-beta

Any help/insight appreciated. Thanks

**Comment by ervinewell** [comment]
I've encountered the same problem!!!

**Comment by akhaku** [comment]
Thanks for the report! Will investigate when I have a moment.

**Comment by stocks29** [comment]
👍
