### ISSUE TITLE
OAuth callback URL must be a string

### ISSUE THREAD

**Issue by ohalligan** [evernote/evernote-sdk-js#70]
Hello there,
I've been developing an application using Electron but I have a problem authenticating users. Most of the times, when I call the getRequestToken function and redirect the user to the login form, evernote throws an error:

```
Uncaught AssertionError: path must be a string
```

This is my code is structured:

```javascript
var Evernote = require('evernote');
var client = new Evernote.Client({
  consumerKey: 'consumer',
  consumerSecret: 'secret',
  sandbox: false
});

client.getRequestToken("http://localhost:53546/", function(error, oauthToken, oauthTokenSecret) {
    if (error) {
    // do your error handling here
    }
    oauthStore.oauthToken = oauthToken;
    oauthStore.oauthTokenSecret = oauthTokenSecret;
    mainWindow.loadURL(client.getAuthorizeUrl(oauthToken)); // send the user to Evernote
});
```

The problem is that 95% of the times, the callback is not called. I even tried it with a different URL (not localhost), but the issue remains.

Thank you.

**Comment by akhaku** [comment]
To be clear - you're saying it errors out before the callback is called, so in the getRequestToken method? Do you have a stack trace?

**Comment by pahund** [comment]
I have the same problem, also trying to authenticate with an Electron app. 

See my relevant code on GitHub: 

https://github.com/pahund/fit17/blob/evernote/src/mainProcess/evernote/index.js

The Evernote login window appears, I enter my credentials, hit submit. 

The user name and password are correct (registered on the Evernote sandbox).

The screen goes blank, Electron's developer console shows this error:

```
"AssertionError: path must be a string
    at Module.require (module.js:497:3)
    at require (internal/module.js:20:19)
    at https://sandbox.evernote.com/ro/Lzk2MWRlZmU5MzJhMDg4NzdkN2M4NmVlZTVjNDFlOTIyZDMyMDg3YzAuanM/L2RhMDJmMDE1MWU5NDc2NzFjMTg5MDcwMzY5ODkyNjI4NWU1YTk5MDcuanM/1659902046.js:81:71"
```

The error message leads me to believe that the error occurs in the JS code of the Evernote sandbox, not in my code.

**Comment by isNeilLin** [comment]
@ohalligan @pahund  I have the same problem. Did you fix it ?

**Comment by isNeilLin** [comment]
@akhaku  Here is stack trace
![image](https://user-images.githubusercontent.com/18683728/45675006-d6374100-bb60-11e8-8834-1dd41696a67f.png)

**Comment by pahund** [comment]
No, I hadn't found a fix or workaround, sorry
