### ISSUE TITLE
Error: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by brpaz** [evernote/evernote-sdk-js#81]
Hello. I cant do requests to Evernote using the SDK. I always get the following error:

```
Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:54:11)
    at Object.request (http.js:26:10)
    at BinaryHttpTransport.module.exports.BinaryHttpTransport.flush (/media/DATA/Code/personal/cerebro-plugin-evernote/dist/index.js:6117:20)
    at BinaryProtocol.module.exports.BinaryProtocol.flush (/media/DATA/Code/personal/cerebro-plugin-evernote/dist/index.js:5569:23)
```

Here is my code:

My code:

```
  this.client = new Evernote.Client({ token: token });

  const userStore = this.client.getUserStore();
  userStore.getUser().then(function (user) {
      console.log(user);
    }).catch((err) => {
      console.error(err);
    });

```

**Comment by 1nzer** [comment]
Hello. https://github.com/evernote/evernote-sdk-js/pull/82 is not published on NPM.

**Comment by akhaku** [comment]
I think I just fixed that - please try again
