### ISSUE TITLE
findNotesMetadata error

### ISSUE THREAD

**Issue by anyinlover** [evernote/evernote-sdk-js#83]
Please look at my error, node 9.3.0 evernote 2.0.5:

```
var filter = new Evernote.NoteStore.NoteFilter({
words: ['markdown'],
ascending: true
});

var spec = new Evernote.NoteStore.NotesMetadataResultSpec({
includeTitle: true
});

noteStore.findNotesMetadata(filter, 0, 10, spec).catch(function (err) {
    console.log(err);
    });
```

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:512:11)
    at Object.BinaryParser.fromString (/Users/michael/.node/node_modules/evernote/lib/thrift/protocol/binaryProtocol.js:500:22)
    at BinaryProtocol.writeString (/Users/michael/.node/node_modules/evernote/lib/thrift/protocol/binaryProtocol.js:148:30)
    at BinaryProtocol.writeType (/Users/michael/.node/node_modules/evernote/lib/thrift/protocol/binaryProtocol.js:168:25)
    at new Thrift.Struct.write (/Users/michael/.node/node_modules/evernote/lib/thrift/thrift.js:532:24)
    at Thrift.Struct.write (/Users/michael/.node/node_modules/evernote/lib/thrift/thrift.js:530:17)
    at Thrift.Method.sendRequest (/Users/michael/.node/node_modules/evernote/lib/thrift/thrift.js:162:15)
    at NoteStoreClient.findNotesMetadata (/Users/michael/.node/node_modules/evernote/lib/thrift/gen-js2/NoteStore.js:1584:8)
    at /Users/michael/.node/node_modules/evernote/lib/stores.js:106:14
    at <anonymous>

A good updated tutorial is needed! Thx

**Comment by akhaku** [comment]
NoteFilter.words is supposed to be a string, not an array. Try replacing `['mardown']` with `'markdown'`?

**Comment by anyinlover** [comment]
thank you, now it works.
